module.exports = {
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SEND: "MESSAGE_SEND",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TYPING: "TYPING",
    VERIFY_USER: "VERIFY_USER",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    LOGOUT: "LOGOUT",
    PRIVATE_MESSAGE:"PRIVATE_MESSAGE"
}